
system:
	@i386-elf-gcc -c string.c -o ../bin/string.bin
	@echo compile: string.c ok	
	@i386-elf-gcc -c stdlib.c -o ../bin/stdlib.bin
	@echo compile: stdlib.c ok
	@i386-elf-gcc -c stdio.c -o ../bin/stdio.bin
	@echo compile: stdio.c ok
